on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        user: ${{ secrets.SFTP_USER }}
        pass: ${{ secrets.SFTP_PASS }}
        # lftp settings
        onlyNewer: true
        # Mirror command options
        remoteDir: '/www/'
        options: '--verbose'
